---
author_info:
  name: Libre Embedded
  email: vaughn@libre-embedded.com
  username: libre-embedded

# CI matrix.
versions: ["3.12", "3.13"]
systems:
  - macos-latest
  - windows-latest

codecov_ubuntu: true
